### ISSUE TITLE
Weird black bars when building and exec'ing

### ISSUE THREAD

**Issue by td-ideabox** [Bargsteen/Starfield#1]
Hi thanks for contributing the project! Really helps figure out how to setup a Helm project!

When I `stack build && stack exec starfield` I can see the window pop up and do what I imagine is intended, but these crazy black bars race up and down the window. Curious if you experienced the same thing?

I'm on OSX High Sierra

I noticed that the original Helm examples are on LTS lts-8.18 according to their `stack.yaml`

https://github.com/z0w0/helm/blob/master/stack.yaml

And when I use that LTS I don't see the black bars in the window. 

![starfield-corrupt-artifacts](https://user-images.githubusercontent.com/10654424/48820040-da6e0f00-ed07-11e8-8f05-2c6242d5eba7.gif)

**Comment by td-ideabox** [comment]
Narrowed it down to a diff between LTS 9.5 and 9.6.

Works on 9.5, broke on 9.6

Here's the diff:
https://www.stackage.org/diff/lts-9.5/lts-9.6

**Comment by Bargsteen** [comment]
Interesting bug. I'll look into it when I have time. Thanks for finding the relevant difference of LTS versions :) 

Also, cool to see my project in your fork of Helm. Perhaps you could add a link to my Github in this [Readme](https://github.com/td-ideabox/helm/tree/master/standalone-examples), then it would be perfect :D

**Comment by td-ideabox** [comment]
Figured it out, the version of Helm on hackage is pretty out of date with the repo. So future users will want to add the repo as a dependency via extra-deps:

In stack.yaml write:

extra-deps:
  - github: td-ideabox/helm
    commit: 474aa264d976379b95458ee43de497f952040d52 
That example is using my own fork of this repo but just replace that with this repo or what not.

Yah absolutely!
